"""
Static bank bonus catalog. Edit this list to add/remove/update offers —
it's separate from data/state.json, which only holds your personal
progress (started dates, checked-off steps, closures).

Each entry:
  id            - stable slug, used as the key in data/state.json. Don't
                  rename once you've started tracking a bonus under it.
  name          - display name
  subtitle      - account name / promo code / expiration, shown under the name
  bonus         - integer dollar amount, drives sorting and the totals bar
  requirement   - freeform summary shown above the checklist
  checklist     - ordered list of short steps a user checks off one by one
  monthly_fee   - freeform fee/waiver text
  exit_text     - freeform explanation of the exit terms
  cooldown_text - freeform eligibility/cooldown explanation
  hold_days     - days after "started" before it's safe to close, used to
                  compute the closure date
  cooldown_days - days after closing before eligible again; use None for
                  offers that are one-time-ever (never eligible again)
"""

BANKS = [
    {
        "id": "us-bank-business",
        "name": "US Bank — Business",
        "subtitle": "Platinum Business Checking, promo Q3AFL26, through 9/27/26",
        "bonus": 1200,
        "requirement": "$25k new money within 30 days; hold as daily balance through day 60; 6 qualifying transactions within 60 days (debit purchases, ACH/wire/Zelle credits or debits, mobile deposit, billpay). Promo code Q3BUS26 has reportedly paid $1,500 with identical requirements.",
        "checklist": [
            "Deposit $25,000+ new money within 30 days",
            "Maintain $25,000 daily balance through day 60",
            "Complete 6 qualifying transactions within 60 days",
        ],
        "monthly_fee": "$30 — waived at $25k avg balance (the hold covers it)",
        "exit_text": "Keep until bonus posts (~day 90–105); assume early-closure fee inside 6 months",
        "cooldown_text": "No US Bank business account in past 12 months",
        "hold_days": 180,
        "cooldown_days": 365,
    },
    {
        "id": "truist",
        "name": "Truist",
        "subtitle": "One Checking, promo code required, through 2/2/27",
        "bonus": 500,
        "requirement": "2+ qualifying direct deposits totaling $2,000+ within 120 days; 20+ qualifying debit card purchases. Sources disagree on the purchase window (90 vs 120 days) — use 90 as the safe deadline.",
        "checklist": [
            "Open online with a current promo code",
            "Set up 2+ direct deposits totaling $2,000+ within 120 days",
            "Complete 20+ qualifying debit card purchases within 90 days",
        ],
        "monthly_fee": "$12 — waived with $500 combined balance or any direct deposit",
        "exit_text": "No early-closure fee found in sources checked; confirm before relying on it",
        "cooldown_text": "Cannot be primary holder on an existing Truist personal checking account, or have closed one on/after 7/14/25 — this is an absolute cutoff date in the offer language, not a rolling window, so treat it as indefinite until Truist issues a new offer",
        "hold_days": 120,
        "cooldown_days": None,
    },
    {
        "id": "chase",
        "name": "Chase",
        "subtitle": "Total Checking + Savings combo",
        "bonus": 900,
        "requirement": "Checking ($300): any qualifying direct deposit within 90 days, no minimum. Savings ($200): $15k new money within 30 days, hold $15k for 90 days. Both (+$400): open together, complete both. Payroll-style ACH only for the DD — confirm the offer is still live before opening.",
        "checklist": [
            "Open checking + savings together",
            "Set up qualifying payroll-style direct deposit (checking, $300)",
            "Deposit $15,000+ new money into savings within 30 days",
            "Hold $15,000 in savings for 90 days (savings, $200)",
        ],
        "monthly_fee": "Checking $12 (waive: $500/mo DD or $1,500 bal); Savings $5 (waive: $300 bal); no fees first 2 statement periods",
        "exit_text": "Safe to close after payout — 6-month clawback clause removed",
        "cooldown_text": "One Chase bonus per 24 months",
        "hold_days": 120,
        "cooldown_days": 730,
    },
    {
        "id": "huntington",
        "name": "Huntington",
        "subtitle": "Platinum Perks Checking",
        "bonus": 600,
        "requirement": "$25k new money within 90 days; keep account open 90 days; no DD needed.",
        "checklist": [
            "Deposit $25,000+ new money within 90 days",
            "Keep the account open for 90 days",
        ],
        "monthly_fee": "$25 — waived at $25k relationship balance",
        "exit_text": "After 90 days open and bonus paid (pays within 14 days of qualifying)",
        "cooldown_text": "New checking customers only — no explicit re-eligibility window stated, assuming 12 months. Only available in CO, IL, IN, KY, MI, MN, OH, PA, SD, WI, WV",
        "hold_days": 104,
        "cooldown_days": 365,
    },
    {
        "id": "four-leaf-fcu",
        "name": "Four Leaf FCU",
        "subtitle": "Formerly Bethpage",
        "bonus": 550,
        "requirement": "$500+ direct deposit within 60 days.",
        "checklist": [
            "Set up $500+ direct deposit within 60 days",
        ],
        "monthly_fee": "None known",
        "exit_text": "Check full terms at signup",
        "cooldown_text": "Very ChexSystems-inquiry sensitive — approval typically wants 0–1 inquiries in the last 1–2 months. No explicit re-eligibility window stated, assuming 12 months",
        "hold_days": 60,
        "cooldown_days": 365,
    },
    {
        "id": "keybank",
        "name": "KeyBank",
        "subtitle": "Key Select Checking",
        "bonus": 500,
        "requirement": "$5,000 in direct deposits within 90 days; pays within 60 days of qualifying.",
        "checklist": [
            "Set up $5,000+ in direct deposits within 90 days",
        ],
        "monthly_fee": "$25 — waived with $15k combined balance or $3k+ DDs per statement cycle",
        "exit_text": "$25 fee if closed within 180 days of opening",
        "cooldown_text": "No KeyBank account in past 12 months",
        "hold_days": 180,
        "cooldown_days": 365,
    },
    {
        "id": "td-bank",
        "name": "TD Bank",
        "subtitle": "Beyond Checking + Signature Savings combo, through 7/30/26",
        "bonus": 500,
        "requirement": "Checking ($300): $2,500+ in qualifying direct deposits within 60 days. Savings ($200): deposit $10,000+ within 20 days and hold it for 90 more days. Qualifying direct deposits are electronic payroll/pension/government-benefit payments only — no P2P or interbank transfers. Listed expiration is 7/30/26 — confirm it's still live before applying.",
        "checklist": [
            "Set up $2,500+ in qualifying direct deposits within 60 days (checking, $300)",
            "Deposit $10,000+ into savings within 20 days",
            "Hold the $10,000+ savings balance for 90 more days (savings, $200)",
        ],
        "monthly_fee": "Beyond Checking $25 — waived with $5,000+/mo DD, $2,500 min daily balance, or $25,000 combined balance",
        "exit_text": "TD has reserved the right to deduct the bonus if the account is closed within 6 months of opening",
        "cooldown_text": "No TD Bank personal checking account, or bonus, in the past 12 months",
        "hold_days": 180,
        "cooldown_days": 365,
    },
    {
        "id": "citi",
        "name": "Citi",
        "subtitle": "Citi Priority / Enhanced Direct Deposit, through 10/22/26",
        "bonus": 475,
        "requirement": "Two Enhanced Direct Deposits totaling $5,000+ within 90 days of account opening. The $475 tier is limited to select markets (reported: NY, CT, MD, VA, DC, CA, NV, NJ, and parts of FL/IL) — offers are ZIP-code targeted, confirm what your specific application link shows. A $325 tier (two Enhanced Direct Deposits totaling $3,000+) is reportedly available nationwide as a fallback.",
        "checklist": [
            "Confirm which tier your application link shows ($475 targeted vs $325 nationwide)",
            "Set up two Enhanced Direct Deposits totaling $5,000+ within 90 days",
        ],
        "monthly_fee": "$12 — waived the month of opening and for 3 statement cycles after; confirm waiver conditions after that window",
        "exit_text": "No early-closure fee found; keep account open and active until the bonus posts",
        "cooldown_text": "No Citi checking account or bonus in the past 365 days; soft pull reported",
        "hold_days": 90,
        "cooldown_days": 365,
    },
    {
        "id": "us-bank-personal",
        "name": "US Bank — Personal",
        "subtitle": "Smartly Checking, through 9/8/26",
        "bonus": 450,
        "requirement": "2+ direct deposits totaling $8k within 90 days ($5k → $350, $2k → $250). Brokerage ACH pushes (e.g. Fidelity) have recent success reports as DD.",
        "checklist": [
            "Set up 2+ direct deposits totaling $8,000 within 90 days",
        ],
        "monthly_fee": "$12 — waived with $1,500 avg balance, $1,500+/mo DDs, or a US Bank credit card",
        "exit_text": "Keep until bonus posts; assume early-closure fee inside 6 months",
        "cooldown_text": "No US Bank consumer checking account or bonus in past 12 months",
        "hold_days": 180,
        "cooldown_days": 365,
    },
    {
        "id": "wells-fargo",
        "name": "Wells Fargo",
        "subtitle": "Everyday Checking",
        "bonus": 425,
        "requirement": "$1,000 in direct deposits within 90 days.",
        "checklist": [
            "Set up $1,000+ in direct deposits within 90 days",
        ],
        "monthly_fee": "$15 — waived with $500+/mo electronic deposits or $1,500 min daily balance",
        "exit_text": "No early closure fee; keep open until bonus pays (~120 days)",
        "cooldown_text": "No WF consumer checking bonus in past 12 months",
        "hold_days": 120,
        "cooldown_days": 365,
    },
    {
        "id": "bmo",
        "name": "BMO",
        "subtitle": "Smart Advantage Checking, promo code required, open by 9/8/26",
        "bonus": 400,
        "requirement": "$4,000 in qualifying direct deposits within 90 days of opening. Bonus pays roughly 100 days after opening; balance must be above zero when it lands. Flat $400 — the older tiers are dead. Written terms exclude teller/ATM/wire/P2P deposits and transfers from any bank or brokerage account, though pushes from Ally, Alliant, Fidelity, Chase, Discover, and Capital One are commonly reported as coding through. Zelle, Venmo, and PayPal do not.",
        "checklist": [
            "Open with a current promo code",
            "Set up $4,000+ in qualifying direct deposits within 90 days",
        ],
        "monthly_fee": "None on Smart Advantage (Smart Money $5, Relationship $25)",
        "exit_text": "$50 early closure fee if closed within 90 days of opening — wait out the 90 days and the payout",
        "cooldown_text": "No BMO personal checking now or closed in past 12 months; one bonus per customer. Primary applicant must reside in AZ, CA, CO, FL, IA, IL, IN, MN, NM, NV, OR, UT, WA, or WI",
        "hold_days": 90,
        "cooldown_days": 365,
    },
    {
        "id": "citizens-bank",
        "name": "Citizens Bank",
        "subtitle": "One Deposit Checking, online offer through 8/30/26",
        "bonus": 400,
        "requirement": "One single direct deposit of $1,000 or more within 60 days of opening. Pays as a \"Balance Builder Bonus\" on the date listed in the offer table. A second $400 structure has circulated as $300 checking (single $500 DD) plus $100 savings — confirm which terms your application link carries before opening. Zelle, Cash App, Venmo, and PayPal are excluded from DD by name.",
        "checklist": [
            "Set up one direct deposit of $1,000+ within 60 days",
        ],
        "monthly_fee": "$9.99 on One Deposit Checking — waived by any one deposit per statement period. Separate $3 fee unless enrolled in online statements",
        "exit_text": "No early termination fee, but the account must be open and active through the payout date",
        "cooldown_text": "Primary signer cannot have been a signer on any Citizens personal checking in the previous 6 months. Available in CT, DC, DE, FL, MA, MD, MI, NH, NJ, NY, OH, PA, RI, VT, VA",
        "hold_days": 90,
        "cooldown_days": 180,
    },
    {
        "id": "first-commonwealth",
        "name": "First Commonwealth Bank",
        "subtitle": "Hometown Checking / Plus / Premium, promo code FCB400, through 7/31/26",
        "bonus": 400,
        "requirement": "$200 for 10+ qualifying transactions within 60 days of opening any personal checking account, no DD required; an additional $200 (to $400 total) by opening Hometown Checking Plus or Premium and depositing $2,000+ within 60 days. Sources disagree on what counts toward the base tier — confirm before relying on it.",
        "checklist": [
            "Open with promo code FCB400",
            "Complete 10+ qualifying transactions within 60 days ($200)",
            "Open Plus/Premium tier and deposit $2,000+ within 60 days ($200 more)",
        ],
        "monthly_fee": "Hometown Checking $2 (waived with eStatements); Plus $10 (waived with $1,000+ deposits or $5,000+ relationship balance); Premium $15 (waived with $2,000+ monthly deposits or $10,000+ relationship balance)",
        "exit_text": "Not stated in sources found — confirm before opening",
        "cooldown_text": "No existing personal checking account with First Commonwealth at time of opening; one bonus per customer. Available in PA, OH, IN, KY, or WV",
        "hold_days": 60,
        "cooldown_days": 365,
    },
    {
        "id": "fulton-bank",
        "name": "Fulton Bank",
        "subtitle": "Simply Checking, through 12/31/26",
        "bonus": 400,
        "requirement": "2 qualifying direct deposits, each $500 or more, plus enroll in eStatements. Bonus credits 4–6 weeks after conditions are met. DD is limited to Social Security, pension, payroll, or unemployment.",
        "checklist": [
            "Enroll in eStatements",
            "Set up 2 qualifying direct deposits of $500+ each",
        ],
        "monthly_fee": "None on Simply Checking",
        "exit_text": "No early account termination fee listed",
        "cooldown_text": "No checking account with any Fulton Financial affiliate in past 24 months; one bonus per person. Available in DE, DC, MD, NJ, PA, VA",
        "hold_days": 100,
        "cooldown_days": 730,
    },
    {
        "id": "mt-bank",
        "name": "M&T Bank",
        "subtitle": "EZChoice / MyChoice Checking, promo code TG, open by 7/31/26",
        "bonus": 400,
        "requirement": "Open by 7/31/26 with promo code TG; qualifying direct deposits totaling $500+ within 90 days of opening. Window closes fast — confirm the offer is still live before starting.",
        "checklist": [
            "Open with promo code TG",
            "Set up $500+ in qualifying direct deposits within 90 days",
        ],
        "monthly_fee": "Varies by checking tier (EZChoice, MyChoice Plus, MyChoice Premium) — check the fee schedule for the one you pick",
        "exit_text": "$50 close-out fee if the account is closed within 180 days of opening",
        "cooldown_text": "Not stated in sources found; assuming 12 months. Available online in CT, DC, DE, MA, MD, ME, NH, NJ, NY, PA, VA, VT, WV",
        "hold_days": 180,
        "cooldown_days": 365,
    },
    {
        "id": "pnc",
        "name": "PNC",
        "subtitle": "Virtual Wallet, offer runs 5/29/26–8/31/26",
        "bonus": 400,
        "requirement": "$5,000 in qualifying direct deposits within 60 days on Virtual Wallet with Performance Select. Base Virtual Wallet pays $100 for $500 in DDs. Reward credits 60–90 days after conditions are met. Strict DD definition: recurring income from an employer or agency only. Don't fund with a credit card — codes as a cash advance.",
        "checklist": [
            "Open Virtual Wallet with Performance Select",
            "Set up $5,000+ in qualifying direct deposits within 60 days",
        ],
        "monthly_fee": "Performance Select $25 — waived with $5,000/mo DD, $5,000 combined avg balance, or $25k across PNC deposit and investment accounts. Base Virtual Wallet $7 — waived with $500 DD or $500 avg balance",
        "exit_text": "Account must still be open when the reward credits (60–90 days out). PNC has reclaimed bonuses on early closure — keep 6+ months",
        "cooldown_text": "No PNC consumer checking now or closed in past 12 months; no PNC promotional premium in past 24 months; one per household",
        "hold_days": 180,
        "cooldown_days": 365,
    },
    {
        "id": "regions-bank",
        "name": "Regions Bank",
        "subtitle": "LifeGreen Checking, through 12/31/26",
        "bonus": 400,
        "requirement": "Register by 12/31/26, open by 1/31/27; direct deposits totaling $1,000+ within 90 days of opening. Some sources describe this as LifeGreen Preferred Checking with a higher deposit tier — confirm which product your application link opens before counting on the $400 figure.",
        "checklist": [
            "Register for the offer, then open the account",
            "Set up $1,000+ in direct deposits within 90 days",
        ],
        "monthly_fee": "$11 — waived with a $1,500 monthly balance or $500 (single)/$1,000 (combined) in direct deposits; drops to $8 with eStatements",
        "exit_text": "No early-closure fee found; bonus credits within 60 days of qualifying",
        "cooldown_text": "Deposits must be new to Regions — no explicit re-eligibility window stated, assuming 12 months. Available in AL, AR, FL, GA, IL, IN, IA, KY, LA, MS, MO, NC, SC, TN, TX",
        "hold_days": 150,
        "cooldown_days": 365,
    },
    {
        "id": "sofi",
        "name": "SoFi",
        "subtitle": "Checking and Savings, direct deposit bonus, through 12/31/26",
        "bonus": 400,
        "requirement": "Set up direct deposit; total Eligible Direct Deposits of $5,000+ within 25 days of the first deposit ($1,000–$4,999.99 pays $50 instead). Must be a new SoFi member, or an existing member who has never enrolled in SoFi direct deposit before.",
        "checklist": [
            "Set up direct deposit",
            "Reach $5,000+ in Eligible Direct Deposits within 25 days of the first one",
        ],
        "monthly_fee": "None — no account, service, or maintenance fees",
        "exit_text": "No stated early-closure penalty; account must be in good standing when the bonus is paid",
        "cooldown_text": "One bonus per SoFi member, ever (not just 12 months) — no state restriction found",
        "hold_days": 30,
        "cooldown_days": None,
    },
    {
        "id": "dollar-bank",
        "name": "Dollar Bank",
        "subtitle": "Everything Checking, promo code CM604 or CHK25, through 8/31/26",
        "bonus": 300,
        "requirement": "$200 Mastercard debit card rebate after cumulative direct deposits of $2,500+ within 90 days of opening; an additional $100 credit at the 1-year anniversary if the account is still active and in good standing. Older sources describe a richer $600 structure — confirm which offer your application link carries.",
        "checklist": [
            "Open with promo code CM604 or CHK25",
            "Reach $2,500+ in cumulative direct deposits within 90 days ($200)",
            "Keep the account open to the 1-year anniversary ($100 more)",
        ],
        "monthly_fee": "None stated for the promotional Everything Checking tier",
        "exit_text": "Not disclosed in sources checked — confirm before opening",
        "cooldown_text": "New customers only — no Dollar Bank checking account open in the past 180 days; one bonus per household. Available within Dollar Bank's OH, PA, VA, and MD markets (roughly branch-distance)",
        "hold_days": 90,
        "cooldown_days": 180,
    },
    {
        "id": "fifth-third-bank",
        "name": "Fifth Third Bank",
        "subtitle": "Momentum Checking, unique offer code required, through 9/30/26",
        "bonus": 300,
        "requirement": "Direct deposits totaling $500+ within 90 days of account opening; must present a unique offer code at opening. Verify you have a current offer code before applying — the public checking-offer landing page returned a dead link during this check, so the code path may have moved.",
        "checklist": [
            "Obtain a current unique offer code",
            "Set up $500+ in direct deposits within 90 days",
        ],
        "monthly_fee": "None on Momentum Checking (Preferred Checking $25, waived at $100,000 combined balance)",
        "exit_text": "No early-closure fee found; bonus posts within 10 business days of meeting requirements",
        "cooldown_text": "Not stated in sources found; assuming 12 months. Available in FL, GA, IL, IN, KY, MI, NC, OH, SC, TN, VA",
        "hold_days": 100,
        "cooldown_days": 365,
    },
    {
        "id": "psecu",
        "name": "PSECU",
        "subtitle": "Pennsylvania State Employees CU, promo code 2026PROMO, through 12/31/26",
        "bonus": 300,
        "requirement": "Two qualifying payroll direct deposits of $500+ each within 100 days of joining; bonus pays within 145 days. Anyone can qualify for membership by joining the Pennsylvania Recreation and Park Society (PRPS) during the application — PRPS dues are $20/year and PSECU credits $10 of it, so it's roughly a $10 net cost to become eligible. No PA residency or state employment needed.",
        "checklist": [
            "Join via PRPS membership add-on (~$10 net) during application",
            "Set up two payroll direct deposits of $500+ each within 100 days",
        ],
        "monthly_fee": "Not found in sources checked — confirm on the application",
        "exit_text": "No early-closure fee found in sources checked",
        "cooldown_text": "Not stated in sources found; assuming 12 months. Membership-based (PRPS), not state-restricted",
        "hold_days": 145,
        "cooldown_days": 365,
    },
]
